# Generated by Django 5.2.6 on 2025-10-31 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('monthly_volume', models.CharField(max_length=50, verbose_name='حجم تولید ماهانه')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('monthly_order_volume', models.CharField(max_length=50, verbose_name='حجم سفارش ماهانه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='workshops.product')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کارگاه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('product_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='نوع محصول')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته\u200cبندی')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('ownership_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='نوع مالکیت')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='وب\u200cسایت')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('total_members', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد نیروهای انسانی')),
                ('area', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='مساحت کارگاه (متر مربع)')),
                ('required_capital', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='سرمایه مورد نیاز (تومان)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تأسیس / شروع فعالیت')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='موقعیت مکانی')),
                ('sales_representative', models.CharField(blank=True, max_length=255, null=True, verbose_name='نمایندگی فروش اختصاصی')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='workshop_covers/', verbose_name='تصویر کاور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'کارگاه',
                'verbose_name_plural': 'کارگاه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='دسته نیرو')),
                ('count', models.IntegerField(verbose_name='تعداد نیرو')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_categories', to='workshops.workshop')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='workshops.workshop'),
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='ماه')),
                ('year', models.IntegerField(verbose_name='سال')),
                ('sales', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='فروش')),
                ('production_amount', models.CharField(max_length=50, verbose_name='میزان تولید')),
                ('equipment_rent', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='اجاره تجهیزات')),
                ('material_costs', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='هزینه مواد اولیه')),
                ('salary_maintenance', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='حقوق و نگهداری')),
                ('total_monthly_value', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='ارزش کل کارگاه')),
                ('profit', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='سود ماهانه')),
                ('profit_percentage', models.FloatField(blank=True, null=True, verbose_name='درصد سود ماهانه')),
                ('fixed_workshop_rent', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='اجاره ثابت زمین/سالن کارگاه')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='workshops.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مدیر عامل')),
                ('description', models.TextField(verbose_name='توضیح مختصر')),
                ('workshop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='workshops.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ (تومان)')),
                ('purpose', models.CharField(max_length=200, verbose_name='هدف سرمایه\u200cگذاری')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='workshops.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workshop_gallery/', verbose_name='تصویر')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان آپلود')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workshops.workshop', verbose_name='کارگاه')),
            ],
            options={
                'verbose_name': 'تصویر کارگاه',
                'verbose_name_plural': 'تصاویر کارگاه\u200cها',
            },
        ),
    ]
