# Generated by Django 5.2.6 on 2025-09-13 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کارگاه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='workshop_covers/', verbose_name='تصویر کاور')),
                ('agency', models.CharField(blank=True, max_length=150, null=True, verbose_name='نمایندگی/شرکت')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='موقعیت مکانی')),
                ('product_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع محصول/خدمات')),
                ('required_capital', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='سرمایه مورد نیاز (تومان)')),
                ('profit_percentage', models.FloatField(default=0.0, verbose_name='درصد سود برای سرمایه\u200cگذار')),
                ('contract_duration', models.IntegerField(default=12, verbose_name='مدت قرارداد (به ماه)')),
                ('contract_details', models.TextField(blank=True, null=True, verbose_name='جزئیات تکمیلی قرارداد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'کارگاه',
                'verbose_name_plural': 'کارگاه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workshop_gallery/', verbose_name='تصویر')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان آپلود')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workshops.workshop', verbose_name='کارگاه')),
            ],
            options={
                'verbose_name': 'تصویر کارگاه',
                'verbose_name_plural': 'تصاویر کارگاه\u200cها',
            },
        ),
    ]
