# Generated by Django 5.2.6 on 2025-09-12 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد')),
                ('name', models.CharField(max_length=255, verbose_name='نام کارگاه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='workshops/')),
                ('representative', models.CharField(max_length=255, verbose_name='نمایندگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('location', models.CharField(max_length=255, verbose_name='موقعیت کارگاه')),
                ('product_type', models.CharField(max_length=255, verbose_name='نوع محصول')),
                ('investment_needed', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سرمایه مورد نیاز')),
                ('funded_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تأمین شده')),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد سود')),
                ('duration_months', models.IntegerField(verbose_name='مدت قرارداد (ماه)')),
                ('contract_details', models.TextField(verbose_name='جزئیات قرارداد')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='کاربر', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workshops/')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='workshops.workshop')),
            ],
        ),
    ]
