# Generated by Django 5.2.6 on 2025-09-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='وبسایت'),
        ),
    ]
